FROM php:7.1.0-apache
WORKDIR /var/www/html

RUN apt-get -y clean && \
    apt-get -y update && \
    apt-get -y install \
    git-sh git \
        curl \
        zlib1g-dev \
        libcurl4-gnutls-dev \
        libssl-dev \
        libicu-dev \
        libpq-dev && \
    pecl install mongodb && \
    pecl install redis-3.1.0 && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl && \
    docker-php-ext-install zip && \
    docker-php-ext-enable mongodb redis zip && \
    docker-php-ext-install -j$(nproc) bcmath curl pcntl

ENV TZ Asia/Jakarta

RUN echo $TZ > /etc/timezone && \
    apt-get install -y tzdata && \
    rm /etc/localtime && \
    ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && \
    dpkg-reconfigure -f noninteractive tzdata

RUN set -ex; \
        apt-get install -y libjpeg-dev libpng-dev; \
        docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
        docker-php-ext-install gd opcache mysqli pdo pdo_mysql pdo_pgsql

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
                echo 'opcache.memory_consumption=128'; \
                echo 'opcache.interned_strings_buffer=8'; \
                echo 'opcache.max_accelerated_files=4000'; \
                echo 'opcache.revalidate_freq=2'; \
                echo 'opcache.fast_shutdown=1'; \
                echo 'opcache.enable_cli=1'; \
        } > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN a2enmod rewrite expires

# Enable php composer
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN rm composer-setup.php

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && apt-get autoremove -y

# Allow Composer to be run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

RUN touch /usr/local/etc/php/php.ini
RUN echo 'log_errors = On' > /usr/local/etc/php/php.ini
RUN echo 'error_log = /dev/stderr' >> /usr/local/etc/php/php.ini
RUN echo 'display_errors = Off' >> /usr/local/etc/php/php.ini
RUN echo 'display_startup_errors = Off' >> /usr/local/etc/php/php.ini
RUN echo 'error_reporting = E_ALL' >> /usr/local/etc/php/php.ini
RUN echo 'safe_mode = Off' >> /usr/local/etc/php/php.ini
RUN echo 'upload_max_filesize = 40M' >> /usr/local/etc/php/php.ini
RUN echo 'post_max_size = 40M' >> /usr/local/etc/php/php.ini
RUN echo 'memory_limit = 256M' >> /usr/local/etc/php/php.ini

# how to build this image: docker build -t registry.awan.io/awan/base/php:7.1 -f Dockerfile-base-php7 .