FROM php:7.0-apache
#COPY ./ /var/www/html/
WORKDIR /var/www/html

RUN apt-get -y clean && \
    apt-get -y update && \
    apt-get -y install \
        curl \
        zlib1g-dev \
        libcurl4-gnutls-dev \
        libssl-dev \
        libicu-dev \
        libpq-dev && \
    pecl install mongodb && \
    pecl install redis-3.1.0 && \
    docker-php-ext-configure intl && \
    docker-php-ext-install intl && \
    docker-php-ext-enable mongodb redis && \
    docker-php-ext-install -j$(nproc) bcmath curl pcntl

RUN set -ex; \
        apt-get install -y libjpeg-dev libpng-dev; \
        docker-php-ext-configure gd --with-png-dir=/usr --with-jpeg-dir=/usr; \
        docker-php-ext-install gd mysqli opcache mysqli pdo pdo_mysql pdo_pgsql

# set recommended PHP.ini settings
# see https://secure.php.net/manual/en/opcache.installation.php
RUN { \
                echo 'opcache.memory_consumption=128'; \
                echo 'opcache.interned_strings_buffer=8'; \
                echo 'opcache.max_accelerated_files=4000'; \
                echo 'opcache.revalidate_freq=2'; \
                echo 'opcache.fast_shutdown=1'; \
                echo 'opcache.enable_cli=1'; \
        } > /usr/local/etc/php/conf.d/opcache-recommended.ini

RUN a2enmod rewrite expires

# Enable php composer
RUN curl -sS https://getcomposer.org/installer -o composer-setup.php
RUN php composer-setup.php --install-dir=/usr/local/bin --filename=composer
RUN rm composer-setup.php

RUN apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && apt-get autoremove -y

# Allow Composer to be run as root
ENV COMPOSER_ALLOW_SUPERUSER 1

#RUN composer install --no-ansi --no-dev --no-interaction --no-progress --no-scripts --optimize-autoloader